### ISSUE TITLE
git meta rebase fails with untracked files

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#209] opened 2017-03-02 19:24 UTC
If you add an untracked file to a submodule (that doesn't conflict with anything incoming), git meta rebase will fail with:

"Error: Unstaged changes exist in workdir
   at Error (native)"

**Comment by bpeabody** [comment] 2017-03-02 20:04
dupe of https://github.com/twosigma/git-meta/issues/105

**Closed** 2017-03-02 20:05 UTC
