### ISSUE TITLE
git-meta fails sometimes when submodules are defined in .git/config but not elsewhere

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#464] opened 2018-01-31 14:05 UTC
Related: https://github.com/twosigma/git-meta/issues/64
Example error:
```
$ git meta submodule status
Error: the path 'openpyxl' does not exist in the given tree
    at Error (native)
```
(Pretty sure there's already an issue for this but can't seem to find it.)

**Comment by bpeabody** [comment] 2018-01-31 20:08
Dupe of https://github.com/twosigma/git-meta/issues/276

**Comment by bpeabody** [comment] 2018-01-31 20:10
Actually, I think these are slightly different. https://github.com/twosigma/git-meta/issues/276 is not about open submodules, but about listing submodules in general. That's something to consider, but is a little more complicated and subtle -- it would require crawling a tree to enumerate submodules, which would probably not be performant unless we wrote it in C++.

**Closed by bpeabody** 2018-01-31 20:10 UTC

**Comment by bpeabody** [comment] 2018-01-31 20:41
OK, after doing some digging, I believe this is essentially a dupe of https://github.com/twosigma/git-meta/issues/276 after all.
